// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityContoso.Data;

#nullable disable

namespace UniversityContoso.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20251125105004_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityContoso.Model.Corso", b =>
                {
                    b.Property<int>("CorsoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorsoID"));

                    b.Property<int?>("Crediti")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessoriID")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorsoID");

                    b.HasIndex("ProfessoriID");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("UniversityContoso.Model.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CorsoID")
                        .HasColumnType("int");

                    b.Property<int>("StudenteID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CorsoID");

                    b.HasIndex("StudenteID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("UniversityContoso.Model.Professori", b =>
                {
                    b.Property<int>("ProfessoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessoriID"));

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssunzione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessoriID");

                    b.ToTable("Professori");
                });

            modelBuilder.Entity("UniversityContoso.Model.Studente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("UniversityContoso.Model.Corso", b =>
                {
                    b.HasOne("UniversityContoso.Model.Professori", "Professore")
                        .WithMany()
                        .HasForeignKey("ProfessoriID");

                    b.Navigation("Professore");
                });

            modelBuilder.Entity("UniversityContoso.Model.Enrollment", b =>
                {
                    b.HasOne("UniversityContoso.Model.Corso", "Corso")
                        .WithMany("Enrollments")
                        .HasForeignKey("CorsoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityContoso.Model.Studente", "Studente")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("UniversityContoso.Model.Corso", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("UniversityContoso.Model.Studente", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
